version: '3'
services:
  youtubecast-videoserver:
    build: .
    image: trevorsharp/youtubecast-videoserver:latest
    container_name: youtubecast-videoserver
    restart: unless-stopped
    volumes:
      - ./content:/content
      - ./cookies.txt:/app/cookies.txt
    ports:
      - 3000:80
    environment:
      - 'VIDEO_QUALITY=2160p'
