version: '3'
services:
  youtubecast-download-api:
    build: ./api
    image: trevorsharp/youtubecast-download-api:latest
    container_name: youtubecast-download-api
    restart: unless-stopped
    volumes:
      - ./content:/content
    environment:
      - 'MAX_DOWNLOADS_PER_FEED=3'
      - 'VIDEO_QUALITY=2160p'
    networks:
      - youtubecast-download-server

  youtubecast-download-server:
    build: ./nginx
    image: trevorsharp/youtubecast-download-server:latest
    container_name: youtubecast-download-server
    restart: unless-stopped
    volumes:
      - ./content:/www/content
    ports:
      - 3000:80
      - 3001:80
    networks:
      - youtubecast-download-server

networks:
  youtubecast-download-server:
