version: '3'
services:
  youtubecast-video-server-api:
    build: ./api
    image: trevorsharp/youtubecast-video-server-api:latest
    container_name: youtubecast-video-server-api
    restart: unless-stopped
    volumes:
      - ./content:/content
    environment:
      - 'VIDEO_QUALITY=2160p'
    networks:
      - youtubecast-video-server

  youtubecast-video-server:
    build: ./nginx
    image: trevorsharp/youtubecast-video-server:latest
    container_name: youtubecast-video-server
    restart: unless-stopped
    volumes:
      - ./content:/www/content
    ports:
      - 3000:80
    networks:
      - youtubecast-video-server

networks:
  youtubecast-video-server:
